name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  ci:
    strategy:
      matrix:
        os:
        - windows-latest
        - macos-latest
        - ubuntu-latest
        node:
        - 12
        - 14
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: npm

    - name: npm ci
      run: npm ci

    - name: npm run build
      run: npm run build

    - name: npm test
      run: npm test
