name: Publish new version
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true
        default: patch

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org
        cache: npm

    - name: npm ci
      run: npm ci

    - name: npm run build
      run: npm run build

    - name: git diff
      run: git diff

    - name: npm version ${{ github.event.inputs.version }}
      run: npm version ${{ github.event.inputs.version }}

    - name: Set git variables
      run: |
        $user = Invoke-RestMethod -Method Get -Uri https://api.github.com/users/${{ github.actor }}
        git config user.name $user.name
        git config user.email ($user.email ?? "${{ github.actor }}@noreply.users.github.com")

    - name: Push new version to GitHub
      run: |
        git add package.json package-lock.json
        git commit -m "Publish ${{ github.event.input.version }}"
        git push --tags

    - name: npm publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
